import { Schema } from 'koishi'
import path from 'path'

export interface RenderColors {
  primaryColor: string
  cardBgColor: string
  statusOngoingColor: string
  statusNextColor: string
  statusFinishedColor: string
}

export const defaultColors: RenderColors = {
  primaryColor: '#52449e',
  cardBgColor: '#E3F2FD',
  statusOngoingColor: '#D32F2F',
  statusNextColor: '#1976D2',
  statusFinishedColor: '#388E3C',
}

export const RenderColorsSchema = Schema.object({
  primaryColor: Schema.string().role('color').default('#52449e').description('🎨 主题色（左侧装饰竖线）'),
  cardBgColor: Schema.string().role('color').default('#E3F2FD').description('📋 个人课表卡片背景色'),
  statusOngoingColor: Schema.string().role('color').default('#D32F2F').description('🔴 进行中状态标签色'),
  statusNextColor: Schema.string().role('color').default('#1976D2').description('🔵 下一节状态标签色'),
  statusFinishedColor: Schema.string().role('color').default('#388E3C').description('🟢 已结束状态标签色'),
})

export interface Config {
  // 💬 消息设置
  enableQuote: boolean
  enableWatingHint: boolean
  starlinkTimeHint: boolean
  starlinkTimeHintText: string
  bindPromptText: string

  // ⚙️ 指令设置
  baseCommand: string
  bindCommand: string
  timetableCommand: string
  showCommand: string
  groupCommand: string
  rankingCommand: string
  weekCommand: string

  // 🖼️ 渲染设置
  renderWaitUntil: 'load' | 'domcontentloaded' | 'networkidle0' | 'networkidle2'
  textFontPath: string
  renderFooterText: string

  // 📁 文件设置
  scheduleFileTempDir: string
  scheduleFileTempDeleteTime: number
  holidayCacheDir: string

  // 🎨 渲染颜色设置
  renderColors: RenderColors

  // 🎭 用户名显示样式
  nameDisplayStyle: 'name-only' | 'name-card' | 'card-name' | 'card-only'

  // 🐛 调试设置
  verboseConsoleLog: boolean
}

export const Config: Schema<Config> = Schema.intersect([

  // 💬 消息设置
  Schema.object({
    enableQuote: Schema.boolean().default(true).description('💬 开启后，本插件发送的所有消息都会引用回复触发指令的消息'),
    enableWatingHint: Schema.boolean().default(true).description('⏳ 是否启用「渲染中，请稍候...」提示消息'),
    starlinkTimeHint: Schema.boolean().default(true).description('⭐ 检测到星链课表时，回复提示消息引导用户使用设置星链时间表命令'),
    starlinkTimeHintText: Schema.string().default('⭐ 星链的分享码或JSON导出不包含时间信息，每节课的时间信息需要单独导出。\n\n请使用「{baseCommand}.{timetableCommand}」上传时间表 JSON。\n\n📤 导出方法：星链 App 右上角竖着的三个点 → 上课时间 → 点击时间表 → ✏️ 编辑符号 → 修改时间，然后点击分享符号导出时间 JSON').role('textarea', { rows: [3, 10] }).description('📝 检测到星链课表时发送的提示文本（支持换行，可用 {baseCommand} 和 {timetableCommand} 占位符）'),
    bindPromptText: Schema.string().default('📥 请发送以下格式的课表数据：\n\t • Yunzai 插件原生 JSON — 粘贴 JSON 文本即可（推荐）\n\t • 星链课表 — 发送分享码或 JSON\n\t • WakeUp 课程表（旧版本 6.0.x）— 发送分享口令\n\n💡 未来可能识别更多格式，请阅读插件 readme.md 或 Koishi WebUI → 插件 usage 查看更新计划。\n\n----------\n\n⚠️ 注意：交互式发送文件可能有兼容问题，建议使用交互式发送文本（分享码或 JSON）或直接在指令后附加参数（课表.绑定 [分享码 / JSON 等]）\n\n----------\n\n⚠️ 提示：WakeUp 课程表高版本已对 API 加强限制 🔒，≥ 6.1.x 无法使用分享口令绑定。如仍在使用新版 WakeUp，建议降级到 6.0.23 ⬇️：\nhttps://gitee.com/vincent-zyu/koishi-plugin-course-schedule/releases/download/WakeUp6.0.23/WakeUp_6.0.23.apk\n\n📖 Yunzai 原生 JSON 格式说明：\nhttps://gitee.com/vincent-zyu/koishi-plugin-course-schedule/blob/main/docs/各种课表格式/Yunzai-Schedule-Plugin原生JSON格式.md').role('textarea', { rows: [3, 10] }).description('📝 绑定指令触发交互式等待时发送的提示文本（支持换行）'),
  }).description('💬 消息设置'),

  // ⚙️ 指令设置
  Schema.object({
    baseCommand: Schema.string().default('课表').description('📋 父级指令名称'),
    __split__: Schema.string().disabled().default('上面是父级指令，下面是字指令').description('_____————上面是父级指令，下面是字指令————_____'),
    bindCommand: Schema.string().default('绑定').description('📥 绑定课表命令名'),
    timetableCommand: Schema.string().default('设置星链时间表').description('⏰ 设置星链时间表命令名'),
    showCommand: Schema.string().default('查看').description('👁️ 查看个人课表命令名'),
    groupCommand: Schema.string().default('群课表').description('👥 查看所有已导入用户课表命令名'),
    rankingCommand: Schema.string().default('排行').description('🏆 查看本周排行命令名'),
    weekCommand: Schema.string().default('周课表').description('📅 查看周课表命令名'),
  }).description('⚙️ 指令设置'),

  // 🖼️ 渲染设置
  Schema.object({
    renderWaitUntil: Schema.union([
      Schema.const('load').description('【load】等待页面与静态资源加载完成，适合当前纯本地 HTML 渲染'),
      Schema.const('domcontentloaded').description('【domcontentloaded】只等待 DOM 构建完成，速度快但更容易过早截图'),
      Schema.const('networkidle0').description('【networkidle0】等待网络连接归零，适合依赖外部资源的页面'),
      Schema.const('networkidle2').description('【networkidle2】等待网络基本空闲，介于 load 与 networkidle0 之间'),
    ]).default('load').description('🖼️ Puppeteer setContent 的 waitUntil 策略'),
    textFontPath: Schema.string().default('').role('textarea', { rows: [2, 5] }).description('🔤 文字字体文件路径（绝对路径，留空则使用系统默认字体）'),
    renderFooterText: Schema.string().default('📚📅🤖 Generated by koishi-plugin-course-schedule\n🌐 Gitee repo: https://gitee.com/vincent-zyu/koishi-plugin-course-schedule').role('textarea', { rows: [3, 10] }).description('📝 图片底部文字（支持换行，留空则不显示）'),
  }).description('🖼️ 渲染设置'),

  // 📁 文件设置
  Schema.object({
    scheduleFileTempDir: Schema.string().default(path.resolve(__dirname, '..', 'cache', 'files')).role('textarea', { rows: [2, 5] }).description('📁 课表文件临时目录（绝对路径）'),
    scheduleFileTempDeleteTime: Schema.number().default(300).description('🗑️ 临时课表文件删除时间（秒），0 或负数表示永不删除'),
    holidayCacheDir: Schema.string().default(path.resolve(__dirname, '..', 'cache', 'holidays')).role('textarea', { rows: [2, 5] }).description('📁 节假日缓存目录（绝对路径）'),
  }).description('📁 文件设置'),

  // 🎨 渲染颜色设置
  Schema.object({
    renderColors: RenderColorsSchema,
  }).role('table').default({ renderColors: defaultColors }).description('🎨 渲染颜色设置'),

  // 🎭 用户名显示样式
  Schema.object({
    nameDisplayStyle: Schema.union([
      Schema.const('name-only').description('🏷️ 只显示用户名'),
      Schema.const('name-card').description('🏷️🪪 用户名（群名片）'),
      Schema.const('card-name').description('🪪🏷️ 群名片（用户名）'),
      Schema.const('card-only').description('🪪 只显示群名片'),
    ]).default('name-card').description('🎭 用户名显示样式<br/><i>（群名片为空时始终显示用户名）</i>'),
  }).description('🎭 用户名显示样式'),

  // 🐛 调试设置
  Schema.object({
    verboseConsoleLog: Schema.boolean().default(false).description('📋 详细控制台调试日志'),
  }).description('🐛 调试设置'),
])

export function formatDisplayName(username: string, nickname: string | undefined, style: Config['nameDisplayStyle']): string {
  if (!nickname) return username || '未知用户'
  switch (style) {
    case 'card-only':
      return nickname
    case 'name-card':
      return `${username}（${nickname}）`
    case 'card-name':
      return `${nickname}（${username}）`
    default:
      return username
  }
}
